apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story 
    spec: 
      containers:
        - name: story
          image: deep04bansal/kub-volume:1
          volumeMounts:
            - mountPath: /app/story
              name: story-volume  # name of volume name to be used for this path
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pvc  # corrected syntax for specifying claimName
