FROM node:14-alpine

WORKDIR /app

#whaterver command we will write in terminal after image name npm will be appended automatically
ENTRYPOINT [ "npm" ]

# since utility container can't keep it up and running in docker-compose