apiVersion: v1
kind: Service # Type of the Kubernetes object
metadata: # Metadata of the service
  name: backend # Name of the service
  labels:
    group: deploy
spec: # Specification of the service 
  selector: # Selector of the service
    app: second-app # Label of the pod to be controlled
  ports: # Ports of the service
    - protocol: TCP # Protocol of the port
      port: 80 # Port number of the service
      targetPort: 8080 # Target port number inside the pod
  type: NodePort # Type of the service